### ISSUE TITLE
When I run rake db:migrate or rake db:drop I get a circular reference.

### ISSUE THREAD

**Issue by pama** [arvand23/cakewalk.io#2]
/Users/pama/.rvm/gems/ruby-2.2.2@cakewalk/gems/activesupport-4.0.2/lib/active_support/values/time_zone.rb:282: warning: circular argument reference - now

**Comment by arvand23** [comment]
I've never seen that error before. I can't even find a time_zone.rb, I've
never modified anything time_zone related in this app.

On Sat, May 23, 2015 at 4:58 PM, Paulo Abreu notifications@github.com
wrote:

> /Users/pama/.rvm/gems/ruby-2.2.2@cakewalk/gems/activesupport-4.0.2/lib/active_support/values/time_zone.rb:282:
> warning: circular argument reference - now
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arvand23/cakewalk.io/issues/2.

## 

Arvand Alviri
Email: aalviri@gmail.com
Mobile: 415-690-9364
Linkedin.com/in/alviri

**Comment by pama** [comment]
No worries, it might be related with ruby 2.2 and rails 4.0.x
